export {default as About } from './About'
export {default as Hello} from './Hello'
export {default as Projects} from './Projects'
export {default as Services} from './Services'
export {default as Contact} from './Contact'
export {default as Story} from './Story'
export {default as Layout} from './Layout'
export {default as Technology} from './Technology'